Add Android TV 0.17 blog post
jellyfin/jellyfin.org pull request #1067
Opened 2024-08-02 21:01 UTC by nielsvanvelzen

Blog post for the upcoming 0.17 release of jf-atv.

> [!CAUTION]
> **!!Do not merge!!** - I'll merge it myself when the release is ready.

2024-08-02 21:01 UTC, nielsvanvelzen commented
![image](https://github.com/user-attachments/assets/08935157-69e6-4acf-af09-97d665bd69ef)

2024-08-02 21:05 UTC, anthonylavado requested changes
Otherwise it looks good. Can't wait!

2024-08-02 21:05 UTC, anthonylavado commented on blog/2024/08-03-android-tv-17/index.mdx
> +Audio normalization support was added to automatically adjust volume levels. This feature prevents sudden volume changes between songs. To
```suggestion
Audio normalization support was added to automatically adjust volume levels for music playback. This feature prevents sudden volume changes between songs. To
```

2024-08-03 09:35 UTC, Shadowghost approved these changes

2024-08-03 09:35 UTC, Shadowghost commented on blog/2024/08-03-android-tv-17/index.mdx
> +Series and seasons now display their respective specials, which were previously available only for movies. Additionally, the search
Are we talking Specials or Extras here?

2024-08-03 10:20 UTC, nielsvanvelzen commented on blog/2024/08-03-android-tv-17/index.mdx
> +Series and seasons now display their respective specials, which were previously available only for movies. Additionally, the search
What web calls "Special Features"

2024-08-03 14:42 UTC, merged