Update index.md
jellyfin/jellyfin.org pull request #1074
Opened 2024-08-11 06:29 UTC by JPVenson

Added TOS section in Rules

2024-08-12 02:11 UTC, felix920506 commented
You should add a changelog section at the bottom of the page

2024-08-12 02:12 UTC, felix920506 commented
Also, isn't the ToS of other platforms part already covered in another section of the rules?

2024-08-12 04:55 UTC, JPVenson commented
> Also, isn't the ToS of other platforms part already covered in another section of the rules?

I dont think so to be frank, thats why i added it^^

2024-08-12 06:47 UTC, Shadowghost commented on docs/general/community-standards/index.md
> +- **Do not engage in, encourage, facilitate or discuss anything that will break the Terms Of Service of other Platforms.** Jellyfin lives in an Ecosystem where it is important to keep a balance of us
```suggestion
- **Do not engage in, encourage, facilitate or discuss anything that will break the Terms of Service of other platforms.** Jellyfin lives in an ecosystem where it is important to keep a balance of user features and the impact on other systems. It is our goal to **not** leave an impact or obtaining a reputation for allowing to use Jellyfin in conjunction with other systems, that were not designed or allowed to be used with Jellyfin to keep other Projects alive and reserved for their intended scopes.
```

2024-08-13 15:49 UTC, joshuaboniface requested changes

2024-08-13 15:49 UTC, joshuaboniface commented on docs/general/community-standards/index.md
> +- **Do not engage in, encourage, facilitate or discuss anything that will break the Terms of Service of other platforms.** Jellyfin lives in an ecosystem where it is important to keep a balance of us
```suggestion
- **Do not engage in, encourage, facilitate or discuss Terms of Service (TOS) violations or suggest configurations that may violate the TOS of any other platforms.** Jellyfin can interface with multiple external services, both internally (e.g. Metadata provides) and by user configuration, each of which has its own requirements and TOS to protect itself. We do not want Jellyfin or its community to develop a reputation for facilitating circumvention or breaking of other services' TOSes or be seen as a problematic member of the wider community. The exact nature of these violations is subject to interpretation on a case-by-case basis based on the service in question and the discussion, and this rule is designed to bring attention to the issue. As a concrete example, the Cloudflare Terms Of Service forbid video streaming behind a normal Cloudflare tunnel; thus, suggesting a user run their instance in this way is a violation of this rule.
```

2024-08-13 15:52 UTC, joshuaboniface approved these changes

2024-08-13 15:54 UTC, merged