refactor: replace PR with Pull Requests
jellyfin/jellyfin.org pull request #1111
Opened 2024-09-10 18:54 UTC by ferferga

People not-so well versed with GH might not know what a PR is.

I didn't thought about this in code review, sorry!
Feel free to close it though, since it can also be argued that if you tinker between PRs you understand what "PR" is.

2024-09-10 19:42 UTC, nielsvanvelzen requested changes
Capitalization should just be "pull request"

2024-09-10 19:53 UTC, ferferga commented
Really good point @nielsvanvelzen, thank you very much! 🚀🚀🚀

2024-09-10 19:54 UTC, felix920506 commented on docs/general/testing/web/index.md
> +## Testing pull requests from Cloudflare Pages Deployments
```suggestion
## Testing Pull Requests from Cloudflare Pages Deployments
```
Titles use different capitalization rules than the body

2024-09-10 19:59 UTC, nielsvanvelzen commented on docs/general/testing/web/index.md
> +## Testing Pull Requests from Cloudflare Pages Deployments
Personally I would prefer lowercase here too

```suggestion
## Testing pull requests from Cloudflare Pages Deployments
```

2024-09-10 20:00 UTC, felix920506 approved these changes

2024-09-11 11:33 UTC, nielsvanvelzen approved these changes

2024-09-11 11:35 UTC, merged