Update social.png in meta tags to fix cache on some services
jellyfin/jellyfin.org pull request #1169
Opened 2024-10-26 18:24 UTC by nielsvanvelzen

Some services are still caching our old social.png with the old logo. Updating the URL with a cache buster should solve this.

2024-10-26 18:33 UTC, thornbill reviewed
Maybe use the date or year?

2024-10-26 18:44 UTC, ferferga requested changes
If we had this image imported by the bundler (https://docusaurus.io/docs/static-assets#in-jsx), it would have cache busting by default, instead of relying in copying static assets at the output path after build, which is flakey as we're seeing.

Ser also "Import statement" section from: https://docusaurus.io/docs/markdown-features/assets#images

2024-10-26 19:00 UTC, nielsvanvelzen commented
This is part of the docusaurus config though, so no we can't bundle it without circumventing the config.

2024-10-26 19:09 UTC, ferferga commented
@nielsvanvelzen It shouldn't matter since the config is also JS. I you want I can do it, can I push to this PR?

2024-10-26 19:11 UTC, nielsvanvelzen commented
Yeah sure, if you can figure it out go ahead. But AFAIK the config is handled differently from all other sources.

2024-11-04 08:47 UTC, ferferga commented
@nielsvanvelzen You're right and the solution I could come up with is very convoluted and not worth it because it requires an additional webpack config for the docusaurius config file.

I think the best course of action long term is to follow Astro's approach: Config file is just for building, while all the page configuration lies in the page files themselves as JSX elements (see [Astro SEO](https://github.com/jonasmerlin/astro-seo?tab=readme-ov-file#how-to-use) docs).

Not sure though if that's suitable for this PR, what do you think?

2024-11-04 09:24 UTC, nielsvanvelzen commented
I think we should prefer the built-in configuration options of Docusaurus, otherwise we'll probably run into issues when upgrading versions.

2024-11-11 14:09 UTC, ferferga approved these changes

2024-11-11 16:43 UTC, merged