Add Fladder client
jellyfin/jellyfin.org pull request #1196
Opened 2024-11-09 12:46 UTC by PartyDonut

2024-11-09 12:50 UTC, JPVenson approved these changes

2024-11-09 22:27 UTC, thornbill requested changes
Fladder should have a distinct logo. Reusing the Jellyfin logo in such a blatant manner is something we discourage.

2024-11-09 22:27 UTC, thornbill commented on src/data/clients.ts
> +    platforms: [Platform.Linux, Platform.Windows, Platform.MacOS, Platform.Android, Platform.IOS, Platform.Docker, Platform.Browser],
I don't think Docker is used for clients.

2024-11-11 19:06 UTC, PartyDonut commented
> Fladder should have a distinct logo. Reusing the Jellyfin logo in such a blatant manner is something we discourage.

The icon for Fladder has been changed

2024-11-20 20:42 UTC, PartyDonut commented
@thornbill 
I think all requested changes have been addressed?
If I missed something let me know.

2024-12-14 17:11 UTC, thornbill commented
Sorry for the delay and thanks for updating the logo. The only other feedback I have is maybe iOS shouldn't be listed since it isn't available in the App Store and alternate installation methods aren't achievable for the average user. 🤷‍♂️

2024-12-28 09:17 UTC, PartyDonut commented
iOS has been removed from the clients list.
Personally I would have preferred to keep it in there, but I also udnerst

2024-12-28 09:18 UTC, PartyDonut commented
I've removed iOS from the list 👍🏼 .

Would have preferred to keep it in there but I understand that the installation method doesn't make it feasible for most users.

2025-01-04 21:11 UTC, nielsvanvelzen approved these changes

2025-01-05 01:15 UTC, thornbill approved these changes

2025-01-05 09:30 UTC, merged