Create Nginx Proxy Manager networking webpage
jellyfin/jellyfin.org pull request #767
Opened 2023-12-06 08:24 UTC by Ladrien-git

Nginx Proxy Manager is quite restrictive on what it allows you to do, and because of that the regular Nginx guide does not really apply without spending hours changing settings to see what works.

So I made a guide specifically for Nginx Proxy Manager.

2023-12-06 08:39 UTC, JPVenson commented on docs/general/networking/nginxproxymanager.md
> +    add_header Content-Security-Policy "default-src https: data: blob: http://image.tmdb.org; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.gstatic.com/cv/js/sender/
youtube?

2023-12-06 18:01 UTC, nielsvanvelzen commented
I don't think we need a dedicated page for nginx proxy manager, it would fit better as a subsection in the existing nginx page.

2023-12-06 19:35 UTC, nielsvanvelzen requested changes

2023-12-06 19:35 UTC, nielsvanvelzen commented on docs/general/networking/nginx.md
> +[Nginx Proxy Manager](https://nginxproxymanager.com/) (pronounced "engine X") was created by jc21 in 2016 and provides an easy-to-use web GUI for Nginx.
Pronounciation is wrong as it skips the "proxy manager" part. I also don't think it's worth mentioning that part. Just tell us what the tool is, a jellyfin documentation reader doesn't care who made it and how they pronounce it.

2023-12-06 19:35 UTC, nielsvanvelzen commented on docs/general/networking/nginx.md
> +### Nginx Proxy Manager from a subdomain (jellyfin.example.org)
This title could be skipped

2023-12-06 19:35 UTC, nielsvanvelzen commented on docs/general/networking/nginx.md
> +:::
Why duplicate this tip when already mentioned above in this same document?

2024-01-21 17:58 UTC, nielsvanvelzen approved these changes

2024-01-21 17:59 UTC, merged

2024-01-21 17:59 UTC, nielsvanvelzen commented
Thanks!