Updated the Synology instructions
jellyfin/jellyfin.org pull request #867
Opened 2024-02-23 12:31 UTC by LeRoid-hub

In this RP i updated the Synlogy instruction for DSM 7.

2024-02-27 00:04 UTC, JPVenson commented on docs/general/installation/synology.md
> +
I navigate towards including a disclaimer pointing towards our hardware selection guide with a clear warning that Prebuild nas systems are generally discouraged to be used.

```suggestion
:::caution Pre-built NAS Devices

Many pre-built NAS devices are underpowered. We generally do not recommend running Jellyfin on those devices.
See: [Hardware Selection](https://jellyfin.org/docs/general/administration/hardware-selection#normal-server) for more information.

:::
```

2024-02-27 22:59 UTC, felix920506 requested changes

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +A new window will open, there you can select a version of Jellyfin. We recommend using the latest version. Click "Apply".
```suggestion
A new window will open and a Jellyfin version can be selected for install. The latest version is recommended. Click `Apply` after selection a version.
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +After a few seconds, the image will be downloaded and you can find it in the "Image" tab.
```suggestion
After the image is downloaded, it can be found in the `Image` tab.
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +Navigate to the "Container" tab and click "Create".
```suggestion
Navigate to the `Container` tab and click `Create`.
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +Select the "Jellyfin" image and give the container a name. We recommend using "Jellyfin" as the name. You can also set the container to auto-start if you want Jellyfin to start when the NAS boots.
```suggestion
Select the `Jellyfin` image and give the container a name. This is mainly for identification purposes and can be set to anything desired. `Auto-start` can be enabled to automatically start Jellyfin when the NAS boots.
```
I don't see any "auto-start" options in the included images. Please clarify

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +Also, you can set the resource limits for the container. We recommend that you let the container use all available resources.
```suggestion
Resource limits can also be set for the container. It is recommended that all CPU resources and at least 4GB of ram be allocated to the Jellyfin container.
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +Click "Next".
```suggestion
Click `Next` to proceed to the next step.
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +**Port Settings**
```suggestion
#### Port Settings

```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +You need to set the port settings for the container. Jellyfin uses port 8096 for the web interface and 1900 for DLNA. You can set the container to use the same ports as the host or use different port
```suggestion
Allocate ports to the container. Jellyfin uses port 8096 for the web interface and 1900 for DLNA by default. It is recommended to use the default ports if they are not being used by other services.
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +**Volume Settings**
```suggestion
#### Volume Settings

```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +You need to set the volume settings for the container. Jellyfin needs access to your media files and configuration files.
```suggestion
This setting maps directories on the host to within the container. Use this setting to allow Jellyfin access to media and a place to store application data.
```
A recommendation on how a typical setup should look like should be included.

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +To add a volume, click "Add Folder" and select the folder you want to use. In the middle column, you need to set the mount path. For the media files, you can use "/media" and for the configuration fi
```suggestion
To add a volume, click "Add Folder" and select the folder desired. The mount point is set in the middle column and the directory will be accessible at this path within the container. For media files, `/media` can be used, and for config files, `/config` can be used.
```
There should also be recommendations on where the config directory should be stored on the host system.

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +**Network Settings**
```suggestion
#### Network Settings
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +You need to set the network settings for the container. Jellyfin needs access to the network to stream media and use DLNA. You can use "Bridge" mode if you are running multiple instances of Jellyfin
```suggestion
Set how the container connects to the network. DLNA requires `Host` mode to function.
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +Any other settings can be left as default.
```suggestion
Other settings can be left as default.
```
There should also be explainers on what other settings do for advanced users.

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +![Advanced Settings](/images/docs/install-synology-13.png)
Where is the directory for config files?

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +Click "Next".
```suggestion
Click `Next` to proceed to the next step.
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +You can now see the container in the "Container" tab.
```suggestion
Settings can be reviewed at this screen. Check the `Run this container after the wizard is finished` checkbox and click `Apply` if everything looks correct. The container should now be shown in the `Container` tab.
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +If you used a different port, replace 8096 with the port you used.
```suggestion
Browse to `http://SERVER_IP:8096` in a browser on a other device to finish setting up the Jellyfin server.
If a different port was used, replace `8096` with the port used instead.
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +## earlier versions of DSM
```suggestion
## Earlier Versions of DSM
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +# Install on Synology
```suggestion
# Installation on Synology
```

2024-02-27 22:59 UTC, felix920506 commented on docs/general/installation/synology.md
> +If you used a different port, replace 8096 with the port you used.
```suggestion
If a different port was used, replace `8096` with the port used instead.
```

2024-02-28 09:34 UTC, LeRoid-hub commented on docs/general/installation/synology.md
> +If you are running an older version of DSM, you can use the guide at the bottom.
The Old instructions only apply for machines befor 2016 so i scraped them.

2024-02-28 11:06 UTC, Zelaf commented
Some input:
* DLNA port specification can be ignored under the port section. Instead add the note that it requires `host` and uses the DLNA port 1900 under the network mode to reduce redundancy.
* This will not use hardware tanscoding, on my setup I used the built-in "Projects" function instead to use compose files. Without tanscoding most lower end Synologies will completely halt when transcoding starts. The Synology will not be responsive for several minutes and upwards of 20 minutes afterwards, at least from my experience on using it on my DS720+.
* A recommendation about upgrading the RAM for devices with 2GB or less should be added. The UI will be painfully slow without it. After I put a 16 gig stick in mine it was very performant. This might also be resolvable by using an external SSD or nvme SSD volume, as supported by the newer ones.

I did wrote a guide I never got the time to PR a while back with tanscoding and security in mind. I took screenshots as well. We might be able to incorporate both of them in some way.

2024-02-28 12:07 UTC, JPVenson commented
@Zelaf 

- The DLNA port is irrelevant if you dont use host mode anyway which is required for the feature to work.
- I think that all Hardware requirements are flat handled via the top disclaimer that its generally a bad idea to run a media server on something that is not at all capable of handing the expected demand. 
All those information, minimum RAM, GPU and disk speed are talked about in the provided link to the hardware selection guide and we dont want to fragment those information again.

2024-02-28 13:37 UTC, Zelaf commented
> @Zelaf
> 
>     * The DLNA port is irrelevant if you dont use host mode anyway which is required for the feature to work.
> 
>     * I think that all Hardware requirements are flat handled via the top disclaimer that its generally a bad idea to run a media server on something that is not at all capable of handing the expected demand.
>       All those information, minimum RAM, GPU and disk speed are talked about in the provided link to the hardware selection guide and we dont want to fragment those information again.

Very true! But there of moving the mention of the port 1900 under port settings and noting it down under Network Settings would, imo, streamline the reading as well as people who prefers to skim documentation could find mentions of the DLNA `host` requirement easier to cause less possible confusion.

As for the hardware limitations, reading over it again in full it should indeed cover it. Will certainly be better than what is shown now, which is nothing!

I do hope this will ease the process for the many Synology users. I'd still like to see what the maintainers thoughts on providing a compose guide would be and if that guide should perhaps be under a separate section of this page or perhaps even included in the hardware acceleration page? The process is similar and still handled through the GUI.

2024-02-28 13:56 UTC, JPVenson commented
Thats why there is a disclaimer at the very start of the proposed doc that links to the hardware guide.
Esp. the warnings with low hardware systems.

Our docs are quite extensive how to use compose files with hardware acceleration
https://jellyfin.org/docs/general/installation/container#with-hardware-acceleration
That is covered there well and good.

2024-04-15 17:59 UTC, felix920506 commented
@LeRoid-hub is this ready for re-review?

2024-07-23 12:04 UTC, Gauvino requested changes

2024-07-23 12:04 UTC, Gauvino commented on docs/general/installation/synology.md
> +Settings can be reviewed at this screen. Check the `Run this container after the wizard is finished` checkbox and click `Apply` if everything looks correct. The container should now be shown in the `
```suggestion
Settings can be reviewed on this screen. Check the `Run this container after the wizard is finished` checkbox and click `Apply` if everything looks correct. The container should now be shown in the `Container` tab.
```

2024-07-23 12:04 UTC, Gauvino commented on docs/general/installation/synology.md.orig
> +For [Synology](https://www.synology.com/en-us/dsm), Jellyfin is installed using Docker. For this guide, the Synology Container Manager will be used to install Jellyfin.
```suggestion
For [Synology](https://www.synology.com/en-us/dsm), Jellyfin is installed using Docker. In this guide, the Synology Container Manager will be used to install Jellyfin.
```

2024-07-23 12:04 UTC, Gauvino commented on docs/general/installation/synology.md.orig
> +A new window will open and a Jellyfin version can be selected for install. The latest version is recommended. Click `Apply` after selection a version.
```suggestion
A new window will open and a Jellyfin version can be selected for installation. The latest version is recommended. Click `Apply` after selection a version.
```

2024-07-23 12:04 UTC, Gauvino commented on docs/general/installation/synology.md.orig
> +Settings can be reviewed at this screen. Check the `Run this container after the wizard is finished` checkbox and click `Apply` if everything looks correct. The container should now be shown in the `
```suggestion
Settings can be reviewed on this screen. Check the `Run this container after the wizard is finished` checkbox and click `Apply` if everything looks correct. The container should now be shown in the `Container` tab.
```

2024-07-23 17:35 UTC, LeRoid-hub commented
It would be nice to get this merged i dont have so much time on my hand anymore.

2025-06-24 23:04 UTC, BotBlake requested changes
Hi there!
Sorry that it took so long for this review.
Thank you for your contribution and the time and effort you put into this!

I only have three small points to criticize: 
1. I would say its not required to cite the networking docs here, instead just refer to them 👍 
2. Why are we keeping the old guide? (There is probably a reason to it hat I just missed, right?)
3. I know it was like this before, however new docs PRs try to organize images in subfolders too. Would it be possible to place the images under `/static/images/docs/advanced/synology/{file}`?

Thank you again!
If you need any assistance or discussion, feel free to mention me or respond to this message.

Kind regards

2025-06-24 23:04 UTC, BotBlake commented on docs/general/installation/synology.md
> +#### Port Settings
This would be a great place to reffer to our new Networking Documentation.
https://jellyfin.org/docs/general/post-install/networking/#port-bindings
https://jellyfin.org/docs/general/post-install/networking/dlna#general

That way there isnt any doubled information here that may age differently.

2025-06-24 23:04 UTC, BotBlake commented on docs/general/installation/synology.md.orig
Why are we keeping the old file as `.orig`?
I did not spend the time to read through all the review itterations, but I'd love a quick response here.
At first glance it seems not necessaryto me though.

2025-06-25 00:16 UTC, BotBlake commented
Oh lord, I dont want to talk about this, I am so sorry 😅

2025-06-25 08:19 UTC, LeRoid-hub commented on docs/general/installation/synology.md.orig
I dont know anymore why i kept it as a .orig. 
But i think that i wanted to keep the old docs, so there is instructions on how to get this installed for the previews Synology DSM version. Anyhow I just checked that the current version is for hardware from 2011 and newer.
So I dont think that we need to keep it.

2025-06-25 08:50 UTC, LeRoid-hub commented
Hi @BotBlake 

Thank you for giving this a look.
I think ive done the thinks you found.
I moved the pictures deleted the .orig and refered to the ports and network settings.
Hopefully everythings alright
 
 Have a nice day :)

2025-06-25 08:54 UTC, nielsvanvelzen commented
@LeRoid-hub GitHub still thinks there is a merge conflict on this pull request, looks like @BotBlake's attempt to fix them didn't really work out. Can you take a look at it? Alternatively you can open a new PR.

2025-06-25 09:19 UTC, BotBlake commented
> @LeRoid-hub GitHub still thinks there is a merge conflict on this pull request, looks like @BotBlake's attempt to fix them didn't really work out. Can you take a look at it? Alternatively you can open a new PR.

I can also give fixing it another shot 😆
I still have no idea why the last try went so catastrophically wrong.

2025-06-25 09:29 UTC, LeRoid-hub commented
> > @LeRoid-hub GitHub still thinks there is a merge conflict on this pull request, looks like @BotBlake's attempt to fix them didn't really work out. Can you take a look at it? Alternatively you can open a new PR.
> 
> I can also give fixing it another shot 😆 I still have no idea why the last try went so catastrophically wrong.

This merge conflict is way over my head. And i dont have time to learn how to manage this conflict. 
It would be nice if someone can pick that up. 
And if it dosnt work maybe instructions how i open a new PR. I tried to open a new one like @nielsvanvelzen said, but i just got redirected to this one.
Thank you for your help :)

2025-06-25 15:03 UTC, felix920506 approved these changes

2025-06-25 15:57 UTC, BotBlake requested changes

2025-06-25 15:57 UTC, BotBlake commented on docs/general/installation/advanced/synology.md
> +sidebar_position: 4
Wrongly resolved merge conflict! Sidebar position should be 2, not 4!

2025-06-28 23:33 UTC, BotBlake approved these changes

2025-06-28 23:34 UTC, merged