Refactored the ContactCards using a reusable component
jellyfin/jellyfin.org pull request #905
Opened 2024-03-14 21:51 UTC by PeachesMLG

Refactored the contact cards using a reusable component

2024-03-14 22:46 UTC, felix920506 approved these changes

2024-03-15 06:57 UTC, Shadowghost approved these changes

2024-03-15 17:13 UTC, thornbill requested changes

2024-03-15 17:13 UTC, thornbill commented on src/components/contact/DiscordCard.tsx
> +        body: (
Use children prop instead.

2024-03-15 17:13 UTC, thornbill commented on src/components/contact/ContactCard.tsx
> +  Discord = 'button button--block button--discord',
This seems a bit hacky to include all the classes in this enum.

2024-03-30 15:34 UTC, closed without merging