Update HWA docs for jellyfin-ffmpeg6
jellyfin/jellyfin.org pull request #978
Opened 2024-05-03 14:29 UTC by nyanmisaka

- Update HWA docs for `jellyfin-ffmpeg6`
- Update some relocated links
- Clean the unused ROCm OpenCL docs
- Bump the minimum NVIDIA driver and glibc versions

2024-05-03 14:35 UTC, Gauvino approved these changes
LGTM !

2024-05-03 14:38 UTC, Shadowghost approved these changes

2024-05-03 14:38 UTC, Shadowghost commented on docs/general/administration/hardware-acceleration/nvidia.md
> +You can follow the configuration steps of [Debian And Ubuntu Linux](/docs/general/administration/hardware-acceleration/nvidia#debian-and-ubuntu-linux) but install all Jellyfin packages `jellyfin-serv
```suggestion
You can follow the configuration steps of [Debian and Ubuntu Linux](/docs/general/administration/hardware-acceleration/nvidia#debian-and-ubuntu-linux) but install all Jellyfin packages `jellyfin-server`, `jellyfin-web` and `jellyfin-ffmpeg6` manually from the [Jellyfin Server Releases Page](https://repo.jellyfin.org/releases/server/). Also make sure you choose the correct codename by following the [official version maps](https://linuxmint.com/download_all.php).
```

2024-05-04 00:28 UTC, felix920506 requested changes

2024-05-04 00:28 UTC, felix920506 commented on docs/general/administration/hardware-acceleration/amd.md
> +   - Cons - Windows only, zero-copy supports all GCN+ GPUs.
Why is "supports all GCN+ GPUs a con?

2024-05-04 20:38 UTC, gnattu approved these changes

2024-05-11 19:11 UTC, felix920506 approved these changes

2024-05-11 20:18 UTC, merged